In [1]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import glob
import os

BASE_DIR = "/content/drive/MyDrive/AI351ProjectTest/05-FinalCompilation/"
os.makedirs(BASE_DIR, exist_ok=True)

DOWN_PATH = "/content/drive/MyDrive/AI351ProjectTest/04-DataAugmentation/downsampled.csv"
AUG_PATH_PATTERN = "/content/drive/MyDrive/AI351ProjectTest/04-DataAugmentation/Augmentation*.csv"

Mounted at /content/drive

In [2]:
df_down = pd.read_csv(DOWN_PATH)
df_down["Flag"] = 0

print("Downsampled loaded:", df_down.shape)
df_down.head()

Downsampled loaded: (23762, 7)

,text,label,label_desc,translation,MetricX24_Raw,MetricX24_Scaled_BATAYAN,Flag
0,Normally I hate even thinking about this becau...,0,sadness,Karaniwan akong ayaw mag-isip tungkol dito dah...,0.180561,99.277754,0
1,"You are not alone, trust me. We all face our h...",0,sadness,"Hindi ka nag-iisa, maniwala ka sa akin. Lahat ...",0.221019,99.115925,0
2,i felt like talking too but i didn t know what...,0,sadness,Gusto kong magsalita rin pero hindi ko alam ku...,0.923421,96.306317,0
3,My brother is like my best friend. We are clos...,0,sadness,Ang kapatid ko ay parang pinakamahusay kong ka...,-0.688570,100.000000,0
4,i feel like nobody really care if i m gone eve...,0,sadness,Nararamdaman kong walang tunay na nag-aalala k...,1.094810,95.620761,0

In [3]:
aug_files = sorted(glob.glob(AUG_PATH_PATTERN))

compiled_augmented = []

for file in aug_files:
    # Extract number (e.g., "Augmentation03.csv" → 3)
    filename = os.path.basename(file)
    num = int(filename.replace("Augmentation", "").replace(".csv", ""))

    df_aug = pd.read_csv(file)
    df_aug["Flag"] = num

    compiled_augmented.append(df_aug)
    print(f"Loaded {filename} → Flag = {num}, Shape = {df_aug.shape}")

print("\nTotal augmentation files loaded:", len(compiled_augmented))

Loaded Augmentation01.csv → Flag = 1, Shape = (1400, 7)
Loaded Augmentation02.csv → Flag = 2, Shape = (1400, 7)
Loaded Augmentation03.csv → Flag = 3, Shape = (1400, 7)
Loaded Augmentation04.csv → Flag = 4, Shape = (1400, 7)
Loaded Augmentation05.csv → Flag = 5, Shape = (1400, 7)
Loaded Augmentation06.csv → Flag = 6, Shape = (1400, 7)

Total augmentation files loaded: 6

In [4]:
df_final = pd.concat([df_down] + compiled_augmented, ignore_index=True)

print("FINAL dataset shape:", df_final.shape)
df_final.head()

FINAL dataset shape: (32162, 7)

,text,label,label_desc,translation,MetricX24_Raw,MetricX24_Scaled_BATAYAN,Flag
0,Normally I hate even thinking about this becau...,0,sadness,Karaniwan akong ayaw mag-isip tungkol dito dah...,0.180561,99.277754,0
1,"You are not alone, trust me. We all face our h...",0,sadness,"Hindi ka nag-iisa, maniwala ka sa akin. Lahat ...",0.221019,99.115925,0
2,i felt like talking too but i didn t know what...,0,sadness,Gusto kong magsalita rin pero hindi ko alam ku...,0.923421,96.306317,0
3,My brother is like my best friend. We are clos...,0,sadness,Ang kapatid ko ay parang pinakamahusay kong ka...,-0.688570,100.000000,0
4,i feel like nobody really care if i m gone eve...,0,sadness,Nararamdaman kong walang tunay na nag-aalala k...,1.094810,95.620761,0

In [5]:
OUTPUT_PATH = BASE_DIR + "FinalCompiledDataset.csv"
df_final.to_csv(OUTPUT_PATH, index=False)

print("Saved final merged dataset to:")
print(OUTPUT_PATH)

Saved final merged dataset to:
/content/drive/MyDrive/AI351ProjectTest/06-FinalCompilation/FinalCompiledDataset.csv